### ISSUE TITLE
[settings] save state of checked radio on page refresh

### ISSUE THREAD

**Issue by ogc1231** [ogc1231/festive-quiz-game#105]

**Comment by ogc1231** [comment]
@xiaoniuniu89 any suggestions to get the radio to stay in the correct position on page refresh?

    const dataDifficulty = sessionStorage.getItem('formData');
    const dataQuestion = sessionStorage.getItem('formData');

    if(JSON.parse(dataDifficulty).inlineRadioOptions == 'checked'){
      document.querySelector(
        'input[name="inlineRadioOptions"]:checked'
      ) = true;
    }
    
    if(JSON.parse(dataQuestion).inlineRadioOptions2 == 'checked'){
      document.querySelector(
        'input[name="inlineRadioOptions2"]:checked'
      ) = true;
    }

**Comment by xiaoniuniu89** [comment]
check localStorage.getItem('formData');

if that is there 

```if (savedFormData) {
        const formData = JSON.parse(localStorage.getItem('formData'));
        if (formData.difficultyLevel) {
            document.querySelector(`input[name="inlineRadioOptions"][value="${formData.difficultyLevel}"]`).checked = true;
        }
        if (formData.questionType) {
            document.querySelector(`input[name="inlineRadioOptions2"][value="${formData.questionType}"]`).checked = true;
        }
    }```

**Comment by xiaoniuniu89** [comment]
then attach an event listener to  DOMContent loaded , fire some logic , check local storage and if it is there set the settings

**Comment by ogc1231** [comment]
Thanks seems to be working now
