### ISSUE TITLE
Global Styles and theme

### ISSUE THREAD

**Issue by xiaoniuniu89** [ogc1231/festive-quiz-game#30]
we should have a global style sheet with some consistent themes. 
eg: 

`:root {
  --blue: #1e90ff;
  --white: #ffffff;
}

body {
  background-color: var(--blue);
}`

this will help us have consistent styles across each page and component while also being more maintainable to update a style as we only need to do it from global.css

**Comment by JohnnySonTrinh** [comment]
/* Root variables */
:root {
/* Colours */
--clr-primary-1:hsl(0, 100%, 50%);
--clr-primary-2: hsl(120, 100%, 25%);
/* Secondary colour */
--clr-secondary-1: hsl(51, 100%, 50%);
--clr-secondary-2: hsl(0, 0%, 75%);
--clr-secondary-3: hsl(30, 61%, 50%);
--clr-secondary-4: hsl(231, 100%, 50%);
/* White/black colours */
--clr-white: #ffffff;
--clr-black: #111111;
/* Font family */
--font-christmas: 'Great Vibes', cursive;
}
