### ISSUE TITLE
[Quiz] Pull and  set data from local storage

### ISSUE THREAD

**Issue by ogc1231** [ogc1231/festive-quiz-game#72]

**Comment by xiaoniuniu89** [comment]
users have the option to select a difficulty and type of question from the settings page

in quiz/utils.js we should check if these values are in local storage
if they are add them as part of the queryParams for api
inside of the quiz.js we should apply these values
for example if there is a difficulty , set the timer from 12 seconds to 15 seconds for medium or 20 seconds for easy for example

also points deducted for timeOut could vary depending on difficulty

**Comment by xiaoniuniu89** [comment]
@ogc1231 something similar in quizRules.js

`
function setQuizParameters() {
  let points = 100;
  let time = 12;

  const storedData = localStorage.getItem("formData");
  if (storedData) {
    try {
      const formData = JSON.parse(storedData);
      const difficultyLevel = formData[0].difficultyLevel;

      switch (difficultyLevel) {
        case "easy":
          points = 200;
          time = 20;
          break;
        case "difficult":
          points = 50;
          time = 8;
          break;
      }
    } catch (error) {
      console.error("Error parsing formData from localStorage:", error);
    }
  }

  document.getElementById("points").textContent = points;
  document.getElementById("time").textContent = time;
}

document.addEventListener("DOMContentLoaded", setQuizParameters);

`

**Comment by ogc1231** [comment]
@xiaoniuniu89 tried most of the morning and can't seem to figure this out, Renwar said he would have a go
